# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': '菜品', 'verbose_name_plural': '菜品信息'},
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ProductID',
            field=models.CharField(max_length=18, verbose_name='菜品编号'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ProductName',
            field=models.CharField(max_length=30, verbose_name='菜名'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ProductNumber',
            field=models.CharField(max_length=30, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ProductOffer',
            field=models.CharField(max_length=30, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ProductPrice',
            field=models.PositiveIntegerField(verbose_name='价格'),
        ),
    ]
